<?php
/**
 * Generated by Sentinel · Stage 3 · Test Generation
 * Intent:  TI-013 — My User Tab / Admin access (admin)
 * Rec:     REC-013 — no_observation (confidence 0.90)
 * Level:   api
 * Source:  Venture7\AdminOtp2FA\Controller\Adminhtml\Verify\Resend
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class AdminOtpResendTest extends TestCase
{
    private Client $client;

    protected function setUp(): void
    {
        $this->client = new Client([
            'base_uri'    => $_ENV['MAGENTO_BASE_URL'],
            'http_errors' => false,
        ]);
    }

    /**
     * Resend.php line 35-38: missing OTP session record redirects to admin login.
     * NOTE: Non-determinism risk — Resend.php uses rand(100000, 999999) for OTP
     * generation (line 56). This test cannot assert the OTP value itself.
     */
    public function testResendWithoutSessionRedirectsToAdmin(): void
    {
        $resp = $this->client->get('/adminotp/verify/resend');
        $this->assertContains($resp->getStatusCode(), [302, 403],
            'Resend without a valid OTP session must redirect to admin login');
    }

    /**
     * Resend.php line 43-47: invalid OTP record id in session redirects to admin.
     */
    public function testResendWithInvalidOtpRecordRedirects(): void
    {
        $jar = \GuzzleHttp\Cookie\CookieJar::fromArray(
            ['otp_record_id' => '999999'],
            'localhost'
        );
        $resp = $this->client->get('/adminotp/verify/resend', [
            'cookies' => $jar,
        ]);
        $this->assertContains($resp->getStatusCode(), [302, 403]);
    }

    /**
     * Resend.php line 56: OTP is generated with rand() — test cannot assert
     * the specific OTP value, only that the resend endpoint responds with a
     * success redirect. Missing: verify email was actually dispatched.
     */
    public function testResendWithValidSessionReturnsSuccess(): void
    {
        // Requires a pre-seeded admin session with a valid OTP record
        $adminSession = $_ENV['TEST_ADMIN_OTP_SESSION'] ?? null;
        if (!$adminSession) {
            $this->markTestSkipped('TEST_ADMIN_OTP_SESSION env var not set');
        }

        $resp = $this->client->get('/adminotp/verify/resend', [
            'headers' => ['Cookie' => 'admin_session=' . $adminSession],
        ]);

        // Resend.php redirects to /adminotp/verify/index on success
        $this->assertSame(302, $resp->getStatusCode());
        $this->assertStringContainsString(
            'adminotp/verify/index',
            $resp->getHeaderLine('Location')
        );
    }
}
