<?php
/**
 * Generated by Sentinel · Stage 3 · Test Generation
 * Intent:  TI-009 — MOQ enforcement during checkout (checkout)
 * Rec:     REC-009 — behavior_regressed (confidence 0.97)
 *          REGRESSION: order with qty=1 accepted despite moq_configured=2
 * Level:   api
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class MoqEnforcementTest extends TestCase
{
    private Client $client;
    private string $token;

    protected function setUp(): void
    {
        $this->client = new Client([
            'base_uri'    => $_ENV['MAGENTO_BASE_URL'],
            'http_errors' => false,
        ]);
        $this->token = $this->authenticate(
            $_ENV['TEST_PRIMARY_USER_EMAIL'],
            $_ENV['TEST_PRIMARY_USER_PASSWORD']
        );
    }

    private function authenticate(string $email, string $password): string
    {
        $resp = $this->client->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);
        return trim(json_decode((string) $resp->getBody(), true), '"');
    }

    private function clearCart(): void
    {
        $this->client->delete('/rest/V1/carts/mine', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);
    }

    /**
     * REGRESSION TEST: qty=1 against moq_configured=2 MUST be rejected.
     * OBS-008 shows the system currently accepts this — this test catches the regression.
     */
    public function testOrderBelowMoqIsRejected(): void
    {
        $this->clearCart();

        $addResp = $this->client->post('/rest/V1/carts/mine/items', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['cartItem' => ['sku' => 'CO2-CYLINDER-20LB', 'qty' => 1, 'quote_id' => '']],
        ]);
        $this->assertSame(200, $addResp->getStatusCode());

        $placeResp = $this->client->post('/rest/V1/carts/mine/payment-information', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['paymentMethod' => ['method' => 'stripe_cc']],
        ]);

        $this->assertGreaterThanOrEqual(400, $placeResp->getStatusCode(),
            'Order below MOQ must return HTTP 4xx');
        $this->assertLessThan(500, $placeResp->getStatusCode(),
            'MOQ rejection must be a client error (4xx), not a server error (5xx)');

        $body = json_decode((string) $placeResp->getBody(), true);
        $this->assertNotEmpty($body['message'],
            'MOQ rejection response must include a human-readable error message');
    }

    /** qty at exactly MOQ threshold must be accepted */
    public function testOrderAtMoqThresholdIsAccepted(): void
    {
        $this->clearCart();

        $this->client->post('/rest/V1/carts/mine/items', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['cartItem' => ['sku' => 'CO2-CYLINDER-20LB', 'qty' => 2, 'quote_id' => '']],
        ]);

        $placeResp = $this->client->post('/rest/V1/carts/mine/payment-information', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['paymentMethod' => ['method' => 'stripe_cc']],
        ]);

        $this->assertSame(200, $placeResp->getStatusCode(),
            'Order at MOQ threshold must succeed');
        $orderId = json_decode((string) $placeResp->getBody(), true);
        $this->assertIsInt($orderId);
        $this->assertGreaterThan(0, $orderId);
    }

    /** When CSJ sets MOQ=1 explicitly, a single-unit order must succeed */
    public function testCsjMoqOfOneAllowsSingleUnitOrder(): void
    {
        $this->clearCart();

        // MOQ-1-PRODUCT is a SKU configured with CSJ MOQ = 1 in fixtures
        $this->client->post('/rest/V1/carts/mine/items', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['cartItem' => ['sku' => 'N2-MOQ1-CYLINDER', 'qty' => 1, 'quote_id' => '']],
        ]);

        $placeResp = $this->client->post('/rest/V1/carts/mine/payment-information', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['paymentMethod' => ['method' => 'stripe_cc']],
        ]);

        $this->assertSame(200, $placeResp->getStatusCode(),
            'Single unit order must be accepted when CSJ MOQ = 1');
    }
}
