<?php
/**
 * Generated by Sentinel · Stage 3 · Test Generation
 * Intent:  TI-010 — Checkout page: payment methods section (checkout)
 * Rec:     REC-010 — agree (confidence 0.83)
 * Level:   api
 * Source:  StripeIntegration\Payments\Controller\Customer\PaymentMethods
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class PaymentMethodDeletionTest extends TestCase
{
    private Client $client;
    private string $token;

    protected function setUp(): void
    {
        $this->client = new Client([
            'base_uri'    => $_ENV['MAGENTO_BASE_URL'],
            'http_errors' => false,
        ]);
        $this->token = $this->authenticate(
            $_ENV['TEST_PRIMARY_USER_EMAIL'],
            $_ENV['TEST_PRIMARY_USER_PASSWORD']
        );
    }

    private function authenticate(string $email, string $password): string
    {
        $resp = $this->client->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);
        return trim(json_decode((string) $resp->getBody(), true), '"');
    }

    /** Payment method list endpoint must return available methods */
    public function testPaymentMethodsListReturnsAvailableMethods(): void
    {
        $resp = $this->client->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);

        $this->assertSame(200, $resp->getStatusCode());
        $methods = json_decode((string) $resp->getBody(), true);
        $this->assertIsArray($methods);
        $this->assertNotEmpty($methods, 'At least one payment method must be available');

        $codes = array_column($methods, 'code');
        $this->assertContains('stripe_cc', $codes,
            'Stripe CC must be an available payment method');
    }

    /**
     * PaymentMethods.php line 70-76: deleting a card with an open order must
     * return the specific error message from LocalizedException.
     * Missing test: fingerprint parameter path (PaymentMethods.php line 50).
     */
    public function testCannotDeletePaymentMethodWithOpenOrder(): void
    {
        // Use a known card token that has an associated open order in test fixtures
        $cardToken = $_ENV['TEST_CARD_TOKEN_WITH_OPEN_ORDER'] ?? 'pm_test_open_order';

        $resp = $this->client->get(
            '/stripe/customer/paymentmethods?delete=' . $cardToken,
            ['headers' => ['Authorization' => 'Bearer ' . $this->token]]
        );

        // Should redirect back to payment methods page with error message
        $this->assertContains($resp->getStatusCode(), [200, 302]);
    }

    /** Auto-select behaviour: if only one payment method exists, it must be pre-selected */
    public function testSinglePaymentMethodIsAutoSelected(): void
    {
        $resp = $this->client->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);

        $methods = json_decode((string) $resp->getBody(), true);
        if (count($methods) === 1) {
            $this->assertArrayHasKey('code', $methods[0]);
            $this->assertNotEmpty($methods[0]['code']);
        } else {
            $this->markTestSkipped('Test requires exactly one available payment method');
        }
    }
}
