<?php
/**
 * Generated by Sentinel · Stage 3 · Test Generation
 * Intent:  TI-003 — NAV order entry + SF case creation (checkout)
 * Rec:     REC-003 — behavior_regressed (confidence 0.96)
 *          REGRESSION: sf_case_id=null after order placement
 * Level:   api
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class SfCaseCreationTest extends TestCase
{
    private Client $client;
    private string $token;

    protected function setUp(): void
    {
        $this->client = new Client([
            'base_uri'    => $_ENV['MAGENTO_BASE_URL'],
            'http_errors' => false,
        ]);
        $this->token = $this->authenticate(
            $_ENV['TEST_PRIMARY_USER_EMAIL'],
            $_ENV['TEST_PRIMARY_USER_PASSWORD']
        );
    }

    private function authenticate(string $email, string $password): string
    {
        $resp = $this->client->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);
        return trim(json_decode((string) $resp->getBody(), true), '"');
    }

    /**
     * REGRESSION TEST: After order placement, a Salesforce case MUST be created.
     * Observed system returns sf_case_id=null (OBS-009) — this test will FAIL
     * against the current build and PASS once the SF integration is fixed.
     */
    public function testOrderPlacementCreatesSalesforceCase(): void
    {
        // Add item to cart
        $this->client->post('/rest/V1/carts/mine/items', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['cartItem' => ['sku' => 'CO2-CYLINDER-20LB', 'qty' => 2, 'quote_id' => '']],
        ]);

        // Place order
        $placeResp = $this->client->post('/rest/V1/carts/mine/payment-information', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['paymentMethod' => ['method' => 'stripe_cc']],
        ]);
        $this->assertSame(200, $placeResp->getStatusCode());
        $orderId = json_decode((string) $placeResp->getBody(), true);

        // Fetch order details and assert SF case was created
        $orderResp = $this->client->get("/rest/V1/orders/{$orderId}", [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);
        $this->assertSame(200, $orderResp->getStatusCode());
        $order = json_decode((string) $orderResp->getBody(), true);

        $this->assertNotNull(
            $order['sf_case_id'],
            'sf_case_id must not be null after order placement'
        );
    }

    /** NAV order ID must also be present alongside SF case */
    public function testOrderPlacementCreatesNavEntry(): void
    {
        $this->client->post('/rest/V1/carts/mine/items', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['cartItem' => ['sku' => 'CO2-CYLINDER-20LB', 'qty' => 2, 'quote_id' => '']],
        ]);

        $placeResp = $this->client->post('/rest/V1/carts/mine/payment-information', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['paymentMethod' => ['method' => 'stripe_cc']],
        ]);
        $orderId = json_decode((string) $placeResp->getBody(), true);

        $orderResp = $this->client->get("/rest/V1/orders/{$orderId}", [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);
        $order = json_decode((string) $orderResp->getBody(), true);

        $this->assertNotEmpty($order['nav_order_id'], 'nav_order_id must be present');
    }
}
