<?php

declare(strict_types=1);

/**
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  GENERATED BY SENTINEL  ·  Stage 03 — Test Generation                  │
 * ├─────────────────────────────────────────────────────────────────────────┤
 * │  Generation ID  : GEN-001                                               │
 * │  Intent         : TI-001 — Checkout succeeds after onboarding           │
 * │  Reconciliation : REC-001 — agree (confidence 0.91)                     │
 * │  Source file    : Venture7\BusinessAccount\Controller\Index\Save        │
 * │  Test level     : api                                                   │
 * │  Gate decision  : PASS                                                  │
 * │  Composite score: 91.4                                                  │
 * │  Generated at   : 2026-06-09T08:14:32Z                                  │
 * │  Model          : claude-opus-4-7                                       │
 * ├─────────────────────────────────────────────────────────────────────────┤
 * │  Observations grounding this test:                                      │
 * │  · OBS-001  Login succeeds for Primary user with iOS case +             │
 * │             Approved payment status                                     │
 * │  · OBS-002  No NAV ID present on account at time of onboarding         │
 * │  · OBS-008  Order placement returns HTTP 200 with numeric order_id     │
 * │                                                                         │
 * │  Router rationale:                                                      │
 * │  Behaviour spans an HTTP POST controller that returns JSON —            │
 * │  API level is the right fit. Unit testing OnboardingProcess::execute() │
 * │  would require mocking the entire Magento DI graph. E2E would be too   │
 * │  brittle for a smoke-level regression check.                            │
 * └─────────────────────────────────────────────────────────────────────────┘
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\TestDox;
use PHPUnit\Framework\TestCase;

/**
 * Verifies the full onboarding-to-checkout flow for a business account.
 *
 * Intent: A Primary user with an approved payment status and an iOS case
 * can complete the onboarding save step and subsequently place an order.
 * The checkout must return a valid numeric order ID.
 */
#[Group('sentinel-generated')]
#[Group('integration')]
#[Group('business-account')]
class OnboardingProcessTest extends TestCase
{
    private Client $http;
    private string $customerToken;

    // ── Setup ─────────────────────────────────────────────────────────────────

    protected function setUp(): void
    {
        parent::setUp();

        $this->http = new Client([
            'base_uri'    => (string) getenv('MAGENTO_BASE_URL'),
            'http_errors' => false,
            'timeout'     => 10.0,
        ]);

        $this->customerToken = $this->authenticate(
            (string) getenv('TEST_PRIMARY_USER_EMAIL'),
            (string) getenv('TEST_PRIMARY_USER_PASSWORD'),
        );
    }

    // ── Group 1: Onboarding save endpoint ────────────────────────────────────

    /**
     * OBS-001 confirmed this path returns 200 for an authenticated Primary
     * user posting valid onboarding data including an iOS case and an
     * Approved payment_status.
     */
    #[TestDox('Save endpoint returns 200 for an authenticated Primary user with valid payload')]
    public function testSaveReturns200ForAuthenticatedPrimaryUser(): void
    {
        $response = $this->http->post('/businessaccount/index/save', [
            'headers'     => $this->authHeaders(),
            'form_params' => $this->validOnboardingPayload(),
        ]);

        $this->assertSame(
            200,
            $response->getStatusCode(),
            'POST /businessaccount/index/save must return 200 for a valid authenticated request',
        );
    }

    #[TestDox('Save response body is a JSON object containing a success key')]
    public function testSaveResponseIsJsonWithSuccessKey(): void
    {
        $response = $this->http->post('/businessaccount/index/save', [
            'headers'     => $this->authHeaders(),
            'form_params' => $this->validOnboardingPayload(),
        ]);

        $body = json_decode((string) $response->getBody(), associative: true);

        $this->assertIsArray($body, 'Response body must be a valid JSON object');
        $this->assertArrayHasKey('success', $body, 'Response must contain a "success" key');
        $this->assertTrue((bool) $body['success'], '"success" must be truthy on a valid save');
    }

    /**
     * OBS-002: no NAV ID is expected on the account at the point of onboarding.
     * The field should be absent or null — never a stale value from a prior session.
     */
    #[TestDox('Response does not carry a stale NAV ID when account is newly onboarded')]
    public function testSaveResponseDoesNotContainStaleNavId(): void
    {
        $response = $this->http->post('/businessaccount/index/save', [
            'headers'     => $this->authHeaders(),
            'form_params' => $this->validOnboardingPayload(),
        ]);

        $body = json_decode((string) $response->getBody(), associative: true);

        $this->assertThat(
            $body['nav_id'] ?? null,
            $this->logicalOr($this->isNull(), $this->equalTo('')),
            'nav_id must be absent or null for a freshly onboarded account — OBS-002',
        );
    }

    // ── Group 2: Auth boundary ────────────────────────────────────────────────

    /**
     * Save.php line 70–73: unauthenticated requests must be rejected before
     * any business logic executes.
     */
    #[TestDox('Unauthenticated POST to save is rejected with 302 or 401')]
    public function testUnauthenticatedSaveIsRejected(): void
    {
        $response = $this->http->post('/businessaccount/index/save', [
            'form_params' => $this->validOnboardingPayload(),
        ]);

        $this->assertContains(
            $response->getStatusCode(),
            [302, 401],
            'Unauthenticated save request must redirect to login or return 401',
        );
    }

    // ── Group 3: Post-onboarding checkout flow ────────────────────────────────

    #[TestDox('Cart accepts items after a successful onboarding save')]
    public function testCartAcceptsItemsAfterOnboarding(): void
    {
        $this->performOnboarding();

        $response = $this->http->post('/rest/V1/carts/mine/items', [
            'headers' => $this->authHeaders(),
            'json'    => [
                'cartItem' => [
                    'sku'      => (string) getenv('TEST_PRODUCT_SKU'),
                    'qty'      => 1,
                    'quote_id' => '',
                ],
            ],
        ]);

        $this->assertSame(
            200,
            $response->getStatusCode(),
            'Add-to-cart must succeed for an authenticated user after onboarding',
        );
    }

    /**
     * OBS-008: confirmed that placing an order after the full onboarding flow
     * returns HTTP 200 with a numeric order_id in the response body.
     */
    #[TestDox('Order placement after onboarding returns HTTP 200')]
    public function testOrderPlacementReturns200AfterOnboarding(): void
    {
        $this->performOnboarding();
        $this->addItemToCart();

        $response = $this->http->post('/rest/V1/carts/mine/payment-information', [
            'headers' => $this->authHeaders(),
            'json'    => [
                'paymentMethod' => ['method' => 'stripe_cc'],
                'email'         => (string) getenv('TEST_PRIMARY_USER_EMAIL'),
            ],
        ]);

        $this->assertSame(200, $response->getStatusCode(), 'Order placement must return 200 — OBS-008');
    }

    #[TestDox('Order placement response is a positive numeric order ID')]
    public function testOrderPlacementResponseIsNumericOrderId(): void
    {
        $this->performOnboarding();
        $this->addItemToCart();

        $response = $this->http->post('/rest/V1/carts/mine/payment-information', [
            'headers' => $this->authHeaders(),
            'json'    => [
                'paymentMethod' => ['method' => 'stripe_cc'],
                'email'         => (string) getenv('TEST_PRIMARY_USER_EMAIL'),
            ],
        ]);

        $orderId = json_decode((string) $response->getBody(), associative: true);

        $this->assertIsInt($orderId, 'Response body must be a numeric order ID — OBS-008');
        $this->assertGreaterThan(0, $orderId, 'order_id must be a positive integer');
    }

    /**
     * Regression guard: a second save with the same payload must not error.
     * The endpoint must be idempotent on company_name.
     */
    #[TestDox('Repeated save with the same company name is idempotent')]
    public function testRepeatedSaveIsIdempotent(): void
    {
        $payload = $this->validOnboardingPayload();

        $first  = $this->http->post('/businessaccount/index/save', ['headers' => $this->authHeaders(), 'form_params' => $payload]);
        $second = $this->http->post('/businessaccount/index/save', ['headers' => $this->authHeaders(), 'form_params' => $payload]);

        $this->assertSame(200, $first->getStatusCode(),  'First save must return 200');
        $this->assertSame(200, $second->getStatusCode(), 'Repeated save must also return 200 — endpoint must be idempotent');
    }

    #[TestDox('stripe_cc payment method is available after onboarding')]
    public function testStripeCcIsAvailableAfterOnboarding(): void
    {
        $this->performOnboarding();
        $this->addItemToCart();

        $response = $this->http->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => $this->authHeaders(),
        ]);

        $methods = json_decode((string) $response->getBody(), associative: true) ?? [];
        $codes   = array_column($methods, 'code');

        $this->assertContains(
            'stripe_cc',
            $codes,
            'stripe_cc must be available after onboarding',
        );
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function authHeaders(): array
    {
        return [
            'Authorization' => 'Bearer ' . $this->customerToken,
            'Content-Type'  => 'application/x-www-form-urlencoded',
        ];
    }

    private function validOnboardingPayload(): array
    {
        return [
            'company_name'   => 'Sentinel Test Co. ' . substr(uniqid(), -6),
            'group_id'       => '5',
            'payment_status' => 'Approved',
            'ios_case_id'    => 'SF-CASE-SENTINEL-001',
        ];
    }

    private function performOnboarding(): void
    {
        $this->http->post('/businessaccount/index/save', [
            'headers'     => $this->authHeaders(),
            'form_params' => $this->validOnboardingPayload(),
        ]);
    }

    private function addItemToCart(): void
    {
        $this->http->post('/rest/V1/carts/mine/items', [
            'headers' => $this->authHeaders(),
            'json'    => [
                'cartItem' => [
                    'sku'      => (string) getenv('TEST_PRODUCT_SKU'),
                    'qty'      => 1,
                    'quote_id' => '',
                ],
            ],
        ]);
    }

    private function authenticate(string $email, string $password): string
    {
        $response = $this->http->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);

        $this->assertSame(200, $response->getStatusCode(), 'Test setup failed: could not authenticate test user');

        return trim((string) json_decode((string) $response->getBody(), associative: true), '"');
    }
}
