<?php

declare(strict_types=1);

/**
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  GENERATED BY SENTINEL  ·  Stage 03 — Test Generation                  │
 * ├─────────────────────────────────────────────────────────────────────────┤
 * │  Generation ID  : GEN-010                                               │
 * │  Intent         : TI-010 — Checkout page: payment methods section       │
 * │  Reconciliation : REC-010 — agree (confidence 0.83)                     │
 * │  Source file    : StripeIntegration\Payments\Controller\Customer\       │
 * │                   PaymentMethods                                        │
 * │  Test level     : api                                                   │
 * │  Gate decision  : PASS                                                  │
 * │  Composite score: 84.7                                                  │
 * │  Generated at   : 2026-06-09T08:14:41Z                                  │
 * │  Model          : claude-opus-4-7                                       │
 * ├─────────────────────────────────────────────────────────────────────────┤
 * │  Observations grounding this test:                                      │
 * │  · OBS-005  Standard and Rush delivery methods returned with correct    │
 * │             fields (carrier_code, amount, estimated_delivery)           │
 * │  · OBS-006  Shipping info can be set; payment methods returned          │
 * │  · OBS-007  Two payment methods available at checkout                  │
 * │  · OBS-011  Overused promo code error message matches spec exactly      │
 * │                                                                         │
 * │  Router rationale:                                                      │
 * │  Payment method management is exposed via the Stripe Payments           │
 * │  controller. API-level tests cover the delete-with-open-order guard     │
 * │  (PaymentMethods.php line 70–76) which has a specific, testable         │
 * │  error message. Unit tests would require mocking Stripe's SDK.          │
 * │                                                                         │
 * │  Known non-determinism: Will Call absence in OBS-005 may be            │
 * │  session-specific — Will Call assertions excluded from this file.       │
 * └─────────────────────────────────────────────────────────────────────────┘
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\TestDox;
use PHPUnit\Framework\TestCase;

/**
 * Verifies the payment methods section of the checkout page.
 *
 * Intent: Payment methods must list available options, guard against deleting
 * a card attached to an open order, and return the exact promo-code error
 * string observed in OBS-011.
 */
#[Group('sentinel-generated')]
#[Group('integration')]
#[Group('checkout')]
#[Group('payment-methods')]
class PaymentMethodDeletionTest extends TestCase
{
    private Client $http;
    private string $customerToken;

    // ── Setup ─────────────────────────────────────────────────────────────────

    protected function setUp(): void
    {
        parent::setUp();

        $this->http = new Client([
            'base_uri'    => (string) getenv('MAGENTO_BASE_URL'),
            'http_errors' => false,
            'timeout'     => 10.0,
        ]);

        $this->customerToken = $this->authenticate(
            (string) getenv('TEST_PRIMARY_USER_EMAIL'),
            (string) getenv('TEST_PRIMARY_USER_PASSWORD'),
        );
    }

    // ── Group 1: Payment method list ──────────────────────────────────────────

    /**
     * OBS-007 confirmed two payment methods are available at checkout.
     * We assert count >= 1 to avoid fixture fragility.
     */
    #[TestDox('Payment methods endpoint returns a non-empty list')]
    public function testPaymentMethodsEndpointReturnsNonEmptyList(): void
    {
        $response = $this->http->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => $this->authHeaders(),
        ]);

        $this->assertSame(200, $response->getStatusCode());

        $methods = json_decode((string) $response->getBody(), associative: true);

        $this->assertIsArray($methods, 'Payment methods response must be a JSON array');
        $this->assertNotEmpty($methods, 'At least one payment method must be available — OBS-007');
    }

    #[TestDox('Each payment method object contains required fields: code and title')]
    public function testEachPaymentMethodHasRequiredFields(): void
    {
        $response = $this->http->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => $this->authHeaders(),
        ]);

        $methods = json_decode((string) $response->getBody(), associative: true) ?? [];

        foreach ($methods as $method) {
            $this->assertArrayHasKey('code',  $method, 'Payment method must have a "code" field');
            $this->assertArrayHasKey('title', $method, 'Payment method must have a "title" field');
            $this->assertNotEmpty($method['code'],  '"code" must not be empty');
            $this->assertNotEmpty($method['title'], '"title" must not be empty');
        }
    }

    #[TestDox('stripe_cc is present in the list of available payment methods')]
    public function testStripeCcIsPresentInPaymentMethods(): void
    {
        $response = $this->http->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => $this->authHeaders(),
        ]);

        $methods = json_decode((string) $response->getBody(), associative: true) ?? [];
        $codes   = array_column($methods, 'code');

        $this->assertContains(
            'stripe_cc',
            $codes,
            'stripe_cc must be present — observed as primary payment method in OBS-006, OBS-007',
        );
    }

    // ── Group 2: Deletion guard ───────────────────────────────────────────────

    /**
     * PaymentMethods.php line 70–76: attempting to delete a payment method
     * attached to an open order must not succeed silently.
     * A silent 200 with success=true would be a regression in the guard logic.
     */
    #[TestDox('Deleting a card with an open order does not return a silent success')]
    public function testDeletingCardWithOpenOrderIsBlocked(): void
    {
        $cardToken = (string) (getenv('TEST_CARD_TOKEN_WITH_OPEN_ORDER') ?: 'pm_test_open_order');

        $response = $this->http->get(
            '/stripe/customer/paymentmethods?delete=' . urlencode($cardToken),
            ['headers' => $this->authHeaders()],
        );

        if ($response->getStatusCode() === 200) {
            $body = json_decode((string) $response->getBody(), associative: true);
            $this->assertFalse(
                (bool) ($body['success'] ?? true),
                'Deleting a card with an open order must not return success=true — PaymentMethods.php line 70–76',
            );
        } else {
            $this->assertContains(
                $response->getStatusCode(),
                [302, 400, 403, 422],
                'Blocked deletion must result in a redirect or client error',
            );
        }
    }

    // ── Group 3: Promo code behaviour ─────────────────────────────────────────

    /**
     * OBS-011: the exact error string returned when a promo code is overused.
     * This is a literal string assertion — wording changes are breaking changes.
     */
    #[TestDox('Overused promo code returns the exact error message observed in OBS-011')]
    public function testOverusedPromoCodeReturnsExactErrorMessage(): void
    {
        $response = $this->http->put('/rest/V1/carts/mine/coupons/OVERUSED_PROMO_CODE', [
            'headers' => $this->authHeaders(),
        ]);

        $this->assertStringContainsString(
            'Sorry, this coupon has already been redeemed the maximum number of times at this location',
            (string) $response->getBody(),
            'Overused promo code error message must match the observed string exactly — OBS-011',
        );
    }

    // ── Group 4: Delivery method shape ───────────────────────────────────────

    /**
     * OBS-005: Standard and Rush delivery methods returned with carrier_code,
     * amount, and estimated_delivery. Will Call excluded (session-specific).
     */
    #[TestDox('Shipping methods include Standard and Rush with required fields')]
    public function testShippingMethodsIncludeStandardAndRush(): void
    {
        $this->setShippingAddress();

        $response = $this->http->get('/rest/V1/carts/mine/shipping-methods', [
            'headers' => $this->authHeaders(),
        ]);

        $this->assertSame(200, $response->getStatusCode());

        $methods      = json_decode((string) $response->getBody(), associative: true) ?? [];
        $carrierCodes = array_column($methods, 'carrier_code');

        $this->assertContains('standard', $carrierCodes, 'Standard delivery must be available — OBS-005');
        $this->assertContains('rush',     $carrierCodes, 'Rush delivery must be available — OBS-005');

        foreach ($methods as $method) {
            $this->assertArrayHasKey('amount',             $method, 'Shipping method must include amount');
            $this->assertArrayHasKey('estimated_delivery', $method, 'Shipping method must include estimated_delivery — OBS-005');
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function authHeaders(): array
    {
        return ['Authorization' => 'Bearer ' . $this->customerToken];
    }

    private function setShippingAddress(): void
    {
        $this->http->post('/rest/V1/carts/mine/shipping-information', [
            'headers' => $this->authHeaders(),
            'json'    => [
                'addressInformation' => [
                    'shipping_address'      => [
                        'region'     => 'California',
                        'region_id'  => 12,
                        'country_id' => 'US',
                        'street'     => ['123 Commerce St'],
                        'postcode'   => '94105',
                        'city'       => 'San Francisco',
                        'firstname'  => 'Test',
                        'lastname'   => 'User',
                        'email'      => getenv('TEST_PRIMARY_USER_EMAIL'),
                        'telephone'  => '5551234567',
                    ],
                    'shipping_carrier_code' => 'standard',
                    'shipping_method_code'  => 'standard',
                ],
            ],
        ]);
    }

    private function authenticate(string $email, string $password): string
    {
        $response = $this->http->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);

        $this->assertSame(200, $response->getStatusCode(), 'Test setup failed: could not authenticate test user');

        return trim((string) json_decode((string) $response->getBody(), associative: true), '"');
    }
}
