<?php
/**
 * Generated by Sentinel · Stage 3 · Test Generation
 * Intent:  TI-001 — Checkout succeeds after onboarding (checkout)
 * Rec:     REC-001 — agree (confidence 0.91)
 * Level:   api
 * Source:  Venture7\BusinessAccount\Controller\Index\Save
 * Updated: Sentinel Stage 6 · Test Update (steady-state)
 *          Diff: logger.warning added on invalid-form-key path in Save::execute
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class OnboardingProcessTest extends TestCase
{
    private Client $client;
    private string $token;

    protected function setUp(): void
    {
        $this->client = new Client([
            'base_uri'    => $_ENV['MAGENTO_BASE_URL'],
            'http_errors' => false,
        ]);
        $this->token = $this->authenticate(
            $_ENV['TEST_PRIMARY_USER_EMAIL'],
            $_ENV['TEST_PRIMARY_USER_PASSWORD']
        );
    }

    private function authenticate(string $email, string $password): string
    {
        $resp = $this->client->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);
        $this->assertSame(200, $resp->getStatusCode(), 'Auth failed');
        return trim(json_decode((string) $resp->getBody(), true), '"');
    }

    /** Save.php line 70-73: unauthenticated requests must redirect to login */
    public function testUnauthenticatedRequestRedirectsToLogin(): void
    {
        $resp = $this->client->post('/businessaccount/index/save', [
            'form_params' => ['group_id' => '1'],
        ]);
        $this->assertContains(
            $resp->getStatusCode(),
            [302, 401],
            'Save endpoint must redirect unauthenticated users'
        );
    }

    /** Save.php line 76-88: POST with valid data must return JSON with success key */
    public function testOnboardingPostReturnsJsonWithSuccessKey(): void
    {
        $resp = $this->client->post('/businessaccount/index/save', [
            'headers'     => ['Authorization' => 'Bearer ' . $this->token],
            'form_params' => [
                'company_name'   => 'Test Industrial Co.',
                'group_id'       => '5',
                'payment_status' => 'Approved',
                'ios_case_id'    => 'SF-CASE-TEST-001',
            ],
        ]);

        $this->assertSame(200, $resp->getStatusCode());
        $body = json_decode((string) $resp->getBody(), true);
        $this->assertIsArray($body, 'Save endpoint must return a JSON object');
        $this->assertArrayHasKey('success', $body, 'Response must contain "success" key');
    }

    /** Save.php line 80-82: group_id defaults to current customer group when omitted */
    public function testMissingGroupIdFallsBackToCustomerGroup(): void
    {
        $resp = $this->client->post('/businessaccount/index/save', [
            'headers'     => ['Authorization' => 'Bearer ' . $this->token],
            'form_params' => ['company_name' => 'Fallback Group Test'],
        ]);

        $this->assertSame(200, $resp->getStatusCode());
        $body = json_decode((string) $resp->getBody(), true);
        $this->assertIsArray($body);
    }

    // SENTINEL-UPDATED: logger.warning added on invalid-form-key path — endpoint must still return well-formed JSON error
    public function testInvalidFormKeyReturnsJsonErrorWithoutException(): void
    {
        // SENTINEL-UPDATED: omit form key entirely to trigger the new logger.warning path in Save::execute
        $resp = $this->client->post('/businessaccount/index/save', [
            'headers'     => ['Authorization' => 'Bearer ' . $this->token],
            'form_params' => [
                'company_name' => 'Bad Form Key Test',
                // intentionally no form_key field
            ],
        ]);

        // SENTINEL-UPDATED: new logging block must not raise an exception; response must remain structured JSON
        $this->assertSame(200, $resp->getStatusCode(),
            'Invalid form key path must return 200 JSON — not a 500 from logger misconfiguration');
        $body = json_decode((string) $resp->getBody(), true);
        $this->assertIsArray($body, 'Response must be valid JSON even on invalid-form-key path');
        // SENTINEL-UPDATED: the error response shape is {'success': false, 'message': 'Invalid form key'}
        $this->assertArrayHasKey('success', $body);
        $this->assertFalse($body['success'], 'success must be false for invalid form key');
    }

    /** Full flow: login → onboarding save → proceed to checkout → place order */
    public function testCheckoutSucceedsAfterOnboarding(): void
    {
        // Add item to cart
        $cartResp = $this->client->post('/rest/V1/carts/mine/items', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => ['cartItem' => ['sku' => 'CO2-CYLINDER-20LB', 'qty' => 2, 'quote_id' => '']],
        ]);
        $this->assertSame(200, $cartResp->getStatusCode(), 'Add to cart failed');

        // Place order
        $orderResp = $this->client->post('/rest/V1/carts/mine/payment-information', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
            'json'    => [
                'paymentMethod' => ['method' => 'stripe_cc'],
                'email'         => $_ENV['TEST_PRIMARY_USER_EMAIL'],
            ],
        ]);
        $this->assertSame(200, $orderResp->getStatusCode(), 'Order placement failed');
        $orderId = json_decode((string) $orderResp->getBody(), true);
        $this->assertIsInt($orderId, 'Response must be a numeric order ID');
        $this->assertGreaterThan(0, $orderId, 'order_id must be a positive integer');
    }
}
