<?php
/**
 * Generated by Sentinel · Stage 3 · Test Generation
 * Intent:  TI-010 — Checkout page: payment methods section (checkout)
 * Rec:     REC-010 — agree (confidence 0.83)
 * Level:   api
 * Source:  StripeIntegration\Payments\Controller\Customer\PaymentMethods
 * Updated: Sentinel Stage 6 · Test Update (steady-state)
 *          Diff: added 'complete' to blocked statuses; added trim($token)
 */

namespace Sentinel\Tests\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;

class PaymentMethodDeletionTest extends TestCase
{
    private Client $client;
    private string $token;

    protected function setUp(): void
    {
        $this->client = new Client([
            'base_uri'    => $_ENV['MAGENTO_BASE_URL'],
            'http_errors' => false,
        ]);
        $this->token = $this->authenticate(
            $_ENV['TEST_PRIMARY_USER_EMAIL'],
            $_ENV['TEST_PRIMARY_USER_PASSWORD']
        );
    }

    private function authenticate(string $email, string $password): string
    {
        $resp = $this->client->post('/rest/V1/integration/customer/token', [
            'json' => ['username' => $email, 'password' => $password],
        ]);
        return trim(json_decode((string) $resp->getBody(), true), '"');
    }

    /** Payment method list endpoint must return available methods */
    public function testPaymentMethodsListReturnsAvailableMethods(): void
    {
        $resp = $this->client->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);

        $this->assertSame(200, $resp->getStatusCode());
        $methods = json_decode((string) $resp->getBody(), true);
        $this->assertIsArray($methods);
        $this->assertNotEmpty($methods, 'At least one payment method must be available');

        $codes = array_column($methods, 'code');
        $this->assertContains('stripe_cc', $codes,
            'Stripe CC must be an available payment method');
    }

    /** PaymentMethods.php: deleting a card with an open order must be blocked */
    public function testCannotDeletePaymentMethodWithOpenOrder(): void
    {
        $cardToken = $_ENV['TEST_CARD_TOKEN_WITH_OPEN_ORDER'] ?? 'pm_test_open_order';

        $resp = $this->client->get(
            '/stripe/customer/paymentmethods?delete=' . $cardToken,
            ['headers' => ['Authorization' => 'Bearer ' . $this->token]]
        );

        $this->assertContains($resp->getStatusCode(), [200, 302]);
    }

    // SENTINEL-UPDATED: 'complete' added to blocked statuses — cards on completed orders must now also be blocked
    public function testCannotDeletePaymentMethodWithCompletedOrder(): void
    {
        // SENTINEL-UPDATED: fixture token tied to an order with status='complete', previously allowed, now blocked
        $cardToken = $_ENV['TEST_CARD_TOKEN_WITH_COMPLETED_ORDER'] ?? 'pm_test_completed_order';

        $resp = $this->client->get(
            '/stripe/customer/paymentmethods?delete=' . $cardToken,
            ['headers' => ['Authorization' => 'Bearer ' . $this->token]]
        );

        // SENTINEL-UPDATED: response must be blocked (200 redirect-with-error or 302) — not a successful 204 delete
        $this->assertContains(
            $resp->getStatusCode(),
            [200, 302],
            'Card tied to a completed order must be blocked from deletion'
        );

        // SENTINEL-UPDATED: if response body is JSON, it must carry an error flag
        $body = json_decode((string) $resp->getBody(), true);
        if (is_array($body) && isset($body['error'])) {
            $this->assertTrue($body['error'], 'Response error flag must be true for completed-order block');
        }
    }

    // SENTINEL-UPDATED: trim($token) added — whitespace-padded token must resolve identically to trimmed version
    public function testTokenWithSurroundingWhitespaceIsNormalised(): void
    {
        // SENTINEL-UPDATED: same token as testCannotDeletePaymentMethodWithOpenOrder but with surrounding spaces
        $paddedToken = '  ' . ($_ENV['TEST_CARD_TOKEN_WITH_OPEN_ORDER'] ?? 'pm_test_open_order') . '  ';

        $resp = $this->client->get(
            '/stripe/customer/paymentmethods?delete=' . urlencode($paddedToken),
            ['headers' => ['Authorization' => 'Bearer ' . $this->token]]
        );

        // SENTINEL-UPDATED: trim() means the server must not return 404 or 422 for a recognisable token with spaces
        $this->assertNotContains(
            $resp->getStatusCode(),
            [404, 422],
            'Whitespace-padded token must be normalised — not treated as unrecognised'
        );
    }

    /** Auto-select behaviour: if only one payment method exists, it must be pre-selected */
    public function testSinglePaymentMethodIsAutoSelected(): void
    {
        $resp = $this->client->get('/rest/V1/carts/mine/payment-methods', [
            'headers' => ['Authorization' => 'Bearer ' . $this->token],
        ]);

        $methods = json_decode((string) $resp->getBody(), true);
        if (count($methods) === 1) {
            $this->assertArrayHasKey('code', $methods[0]);
            $this->assertNotEmpty($methods[0]['code']);
        } else {
            $this->markTestSkipped('Test requires exactly one available payment method');
        }
    }
}
